#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
#
# Authors: limanman
# OsChina: http://xmdevops.blog.51cto.com/
# Purpose:
#
"""
# 说明: 导入公共模块
from app import db as _db
from app import create_app
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
# 说明: 导入其它模块


app = create_app()
manager = Manager(app)
migrate = Migrate(app, _db)

manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
